import type { Appointment } from "@/types/appointment";

export const appointments: Appointment[] = [
  {
    id: "apt-1042",
    patient: { name: "Maya Patel", initials: "MP", age: 34 },
    clinician: "Dr. Anika Rao",
    specialty: "General medicine",
    startsAt: "2026-08-28T09:00:00",
    durationMinutes: 30,
    status: "confirmed",
    reason: "Follow-up consultation",
    room: "Room 04",
  },
  {
    id: "apt-1043",
    patient: { name: "Ethan Brooks", initials: "EB", age: 41 },
    clinician: "Dr. Anika Rao",
    specialty: "General medicine",
    startsAt: "2026-08-28T10:00:00",
    durationMinutes: 45,
    status: "pending",
    reason: "Annual wellness visit",
    room: "Room 04",
  },
  {
    id: "apt-1044",
    patient: { name: "Sofia Chen", initials: "SC", age: 28 },
    clinician: "Dr. Martin Cole",
    specialty: "Dermatology",
    startsAt: "2026-08-28T11:15:00",
    durationMinutes: 30,
    status: "confirmed",
    reason: "Skin consultation",
    room: "Room 12",
  },
  {
    id: "apt-1045",
    patient: { name: "Noah Williams", initials: "NW", age: 52 },
    clinician: "Dr. Anika Rao",
    specialty: "General medicine",
    startsAt: "2026-08-28T14:00:00",
    durationMinutes: 30,
    status: "cancelled",
    reason: "Blood pressure review",
    room: "Room 04",
  },
  // Demo data for the seeded Doctor Portal account (see
  // `@/lib/mock-data/doctorAccounts`) so the doctor dashboard has
  // something to show right after signing in.
  {
    id: "apt-1046",
    patient: { name: "Priya Nandan", initials: "PN", age: 37 },
    clinician: "Dr. Leah Fischer",
    specialty: "General medicine",
    startsAt: "2026-09-03T09:30:00",
    durationMinutes: 30,
    status: "confirmed",
    reason: "Follow-up consultation",
    room: "Room 09",
  },
  {
    id: "apt-1047",
    patient: { name: "Marcus Webb", initials: "MW", age: 45 },
    clinician: "Dr. Leah Fischer",
    specialty: "General medicine",
    startsAt: "2026-09-03T11:00:00",
    durationMinutes: 30,
    status: "pending",
    reason: "New patient intake",
    room: "Room 09",
  },
  {
    id: "apt-1048",
    patient: { name: "Grace Kim", initials: "GK", age: 29 },
    clinician: "Dr. Leah Fischer",
    specialty: "General medicine",
    startsAt: "2026-09-04T13:30:00",
    durationMinutes: 45,
    status: "confirmed",
    reason: "Annual wellness visit",
    room: "Room 09",
  },
];
